#!/usr/bin/env python3
"""
Simple Railway Deployment for Crypto Quant Bot
Uses existing Railway configuration for 24/7 cloud deployment
"""

import os
import sys
import subprocess
from datetime import datetime

def check_git():
    """Check if git is available."""
    try:
        result = subprocess.run(['git', '--version'], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False

def setup_environment():
    """Set up environment variables for Railway deployment."""
    print("🔧 Setting up environment variables...")
    
    env_vars = {
        "ALPACA_API_KEY": "PKJYFI6XVZ9UGW85JFVP",
        "ALPACA_SECRET_KEY": "HY2qdRNAX8TSONDcnsqPfNHUp7WzpeHzpsAdNEGZ",
        "ALPACA_PAPER": "true",
        "DRY_RUN": "false",
        "USE_FUTURES": "true",
        "UPDATE_INTERVAL_MINUTES": "10",
        "TRADING_SYMBOLS": "BTCUSD,ETHUSD,SOLUSD,ADAUSD",
        "MAX_PORTFOLIO_ALLOCATION": "0.60",
        "MAX_NET_EXPOSURE": "0.20",
        "MAX_GROSS_LEVERAGE": "1.8",
        "MAX_SINGLE_POSITION": "0.06",
        "MAX_DAILY_DRAWDOWN": "0.15",
        "MAX_WEEKLY_DRAWDOWN": "0.25",
        "POSITION_SIZING_METHOD": "KELLY_OPTIMAL",
        "ENABLE_EMAIL_NOTIFICATIONS": "true",
        "EMAIL_RECIPIENT": "ebullemor@gmail.com",
        "DIGEST_INTERVAL_HOURS": "24",
        "TRADE_NOTIFICATIONS": "true",
        "DAILY_SUMMARY": "true",
        "LOG_LEVEL": "INFO",
        "ENABLE_HEALTH_CHECKS": "true",
        "PERFORMANCE_MONITORING": "true",
        "RISK_MONITORING": "true",
        "POSITION_TRACKING": "true",
        "SIGNAL_MONITORING": "true"
    }
    
    # Create .env file for Railway
    with open(".env", "w") as f:
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Environment variables saved to .env file")

def create_deployment_guide():
    """Create deployment guide."""
    guide = f"""
🚀 CRYPTO QUANT BOT - RAILWAY DEPLOYMENT GUIDE
{'=' * 60}

📅 Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}
🌐 Platform: Railway Cloud
📧 Email Reports: ebullemor@gmail.com
🔄 Operation: 24/7 (True cloud deployment)

✅ CONFIGURATION READY:
• Railway configuration: railway.toml ✅
• Requirements: requirements-railway.txt ✅
• Environment variables: .env ✅
• Dockerfile: Dockerfile ✅

📊 TRADING CONFIGURATION:
• Symbols: BTCUSD, ETHUSD, SOLUSD, ADAUSD
• Max Net Exposure: 20%
• Max Gross Leverage: 1.8
• Max Single Position: 6%
• Daily Drawdown Limit: 15%

🎯 PERFORMANCE TARGETS:
• Monthly Return: 15%
• Max Drawdown: 25%
• Sharpe Ratio: 0.8
• Win Rate: 55%

📧 EMAIL NOTIFICATIONS:
• Daily Trade Summaries: 6:00 PM UTC
• Individual Trade Alerts: Enabled
• Risk Alerts: Enabled
• Performance Reports: Daily

🛡️ RISK MANAGEMENT:
• Real-time exposure monitoring
• Automatic position sizing
• Drawdown protection
• Correlation monitoring

📋 DEPLOYMENT STEPS:
1. Install Railway CLI: npm install -g @railway/cli
2. Login to Railway: railway login
3. Initialize project: railway init
4. Deploy: railway up
5. Monitor: railway logs

🌐 ALTERNATIVE DEPLOYMENT:
If Railway CLI is not available, you can:
1. Go to https://railway.app
2. Create new project
3. Connect your GitHub repository
4. Railway will auto-deploy using existing config

📋 MONITORING COMMANDS:
• Check status: railway status
• View logs: railway logs
• Update deployment: railway up
• Access dashboard: railway dashboard

---
Generated by Crypto Quant Bot Railway Deployment
"""
    
    with open("RAILWAY_DEPLOYMENT_GUIDE.md", "w") as f:
        f.write(guide)
    
    print("✅ Deployment guide saved to RAILWAY_DEPLOYMENT_GUIDE.md")

def check_railway_files():
    """Check if all Railway files are present."""
    required_files = [
        "railway.toml",
        "requirements-railway.txt", 
        "Dockerfile",
        "scripts/run_live_bot.py"
    ]
    
    missing_files = []
    for file in required_files:
        if not os.path.exists(file):
            missing_files.append(file)
    
    if missing_files:
        print("❌ Missing Railway files:")
        for file in missing_files:
            print(f"   • {file}")
        return False
    else:
        print("✅ All Railway files present")
        return True

def main():
    """Main deployment preparation function."""
    print("🎯 RAILWAY CLOUD DEPLOYMENT PREPARATION")
    print("=" * 60)
    print("Preparing your bot for Railway cloud deployment")
    print("This will enable true 24/7 operation!")
    print()
    
    # Check Railway files
    if not check_railway_files():
        print("❌ Please ensure all Railway files are present")
        return False
    
    # Setup environment
    setup_environment()
    
    # Create deployment guide
    create_deployment_guide()
    
    print()
    print("🎉 DEPLOYMENT PREPARATION COMPLETE!")
    print("=" * 40)
    print("✅ Your bot is ready for Railway deployment")
    print("📧 Daily reports will be sent to: ebullemor@gmail.com")
    print("🔄 Bot will run 24/7 in the cloud")
    print()
    
    print("📋 NEXT STEPS:")
    print("1. Install Railway CLI: npm install -g @railway/cli")
    print("2. Login to Railway: railway login")
    print("3. Deploy: railway up")
    print("4. Monitor: railway logs")
    print()
    
    print("🌐 ALTERNATIVE:")
    print("• Go to https://railway.app")
    print("• Create new project")
    print("• Connect your GitHub repository")
    print("• Railway will auto-deploy using existing config")
    print()
    
    print("📖 See RAILWAY_DEPLOYMENT_GUIDE.md for detailed instructions")
    
    return True

if __name__ == "__main__":
    main()
